name: Go workflow

on:
  push:
    branches:
      - master
      - main

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
          cache: false

      - name: Go test
        run: go test -v ./...

      - name: Push version tag
        uses: falokut/version-tag-action@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
